# ADCMController User Config

# RECORD
RECORD_ON = 0
RECORD_PATH = "./data/Log/"

GPS_RECORD_ON = 1
GPS_RECORD_PATH = "./data/GPSLog/"

# THREAD_CFG
SIMUL_ON = 1
Tablet_ON = 0
set_lat = 37.23920546 # 37.24378495
set_lon = 126.77314629 # 126.77514735

# SIMUL_CFG
SIMUL_CYCLE_MS = 10 # ms
CONTROL_CYCLE_MS = 50
GPS_CYCLE_MS = 30

# MAIN_CFG
ADCMRxPort1 = 4092 # GPS Info [MBC:4091, LGU+: 4092] 
ADCMRxPort2 = 3004 # Car Info
ADCMTxPort1 = 4912 # Control
TeleconsRxPort = 3285 # Path Info

TeleconsAddr = "192.168.100.70"
NE5Addr = "192.168.100.88"
REF_FILE = "./ref/path_0.txt"

RefVelocity = 15
