BBPATH =. "${LAYERDIR}:"

FSL_EULA_FILE = "${LAYERDIR}/EULA"

BBFILE_COLLECTIONS += "katech-apd"
BBFILE_PATTERN_katech-apd := "^${LAYERDIR}"
BBFILE_PRIORITY_katech-apd = "9"

BBFILES += " \
        ${LAYERDIR}/recipes-*/*/*.bb \
        ${LAYERDIR}/recipes-*/*/*.bbappend \
        ${LAYERDIR}/classes/*.bb* \
"
BBMASK += "./meta-alb-sdk/recipes-extended/opendds/*"

# Set LAYERSERIES_COMPAT variable for katech-apd layer
# to match the version "kirkstone" of OpenEmbedded-Core
LAYERSERIES_COMPAT_katech-apd = "kirkstone"

RELEASE_BASE ?= "release/bsp42.0"
