# ---------------------------------------------------------- ###
### ---------------- ControlModule Parameter --------------- ###
# ---------------------------------------------------------- ###
# Control
TargetSpeed = 10 # [kph]

# RECORD
GPSRecord = f # default: f
GPSRecordPath = "./data/GPS/" # S32G

# Path Operation 
ReceivePathFlag = f # default: f
ReferenceFile = "./reference/GPS.txt" # S32G
ExternalIp = "192.168.100.99" # S32G IP , 127.0.0.1(로컬 ip)
ExternalPortReceive = 4488 # 경로주는 모듈에서 S32G로 쏘는 포트, 99ip로 4488 port로 소켓이 바인딩
ExternalPortSend = 4444 # 버퍼를 만들어서 4444로 버퍼를 Send하면 받는쪽에서 4444 소켓을 바인딩하면 받는다
ForwardPort = 1785
BackPort = 3862

# Thread
ViewerFlag = f # bool

# Cycle [ms]
MainCycle = 50
MCUReceiveCycle = 30

# Communicate
BroadCastIp = "192.168.100.255"
S32GIp = "192.168.100.99"
S32GPort = 3004 # MCU
MCUIp = "192.168.100.88"
MCUPort = 4912
ViewerIp = "192.168.100.56"
ViewerPortClient = 80 #
ViewerPortServer = 2817
