# ---------------------------------------------------------- ###
### ---------------- ControlModule Parameter --------------- ###
# ---------------------------------------------------------- ###
# Control
TargetSpeed = 10 # [kph]

# RECORD: Path save -> t
GPSRecord = f
GPSRecordPath = "./Log/GPS/KCITY/KCITY_GPS_1109_Car_O"
PathRecord = f
PathRecordPath = "./Log/Path/KCITY/KCITY_Path_1109_Car_O"
IbeoRecord = f
IbeoDataPath = "./Log/Ibeo/KCITY/KCITY_Ibeo_1109_Car_O"
PedRecord = f
PedDataPath = "./Log/Ped/KCITY/KCITY_Ped_1109_Car_O"

# Path Operation: Save Path -> f, Realtime Path(K-city) -> t
ReceivePathFlag = t

ReferenceFile = "./reference/230703-220744_Gps.txt"
#ReferenceFile = "/home/root/sykim/PathSaveModule/GPS/KATECH/KATECH_0914.txt"
#ReferenceFile = "./Log/GPS/KATECH/KATECH_0914.txt"
#ReferenceFile = "./reference/inclinePath1.txt"

ExternalIp = "192.168.100.99"
ForwardPort = 1785
BackPort = 3862

# 4444 4488

# Thread
ViewerFlag = f

# Cycle [ms]
MainCycle = 50

# Communicate
BroadCastIp = "192.168.100.255"
S32GIp = "192.168.100.99"
S32GPort = 3004
MCUIp = "192.168.100.88"
MCUPort = 4912
RadarPort = 3690
ViewerIp = "192.168.100.35"
ViewerPort = 2817
