#!/bin/sh

ifconfig eth0 down

ifconfig eth0 192.168.1.200 netmask 255.255.255.0

sed -i "s/local/192.168.1.200/g" /etc/vsomeip.json

route add 224.244.224.245 eth0

# Add routing table for VCU and someip
# route add 192.168.1.5 pfe0

exit 0

