# --------------------------------------------------- ###
### ---------------- Config Parameter --------------- ###
# --------------------------------------------------- ###
# Control
TargetSpeed = 10 # [kph]

# RECORD: Path save -> t
GPSRecord = f
GPSRecordPath = "./Log/GPS/KATECH/KATECH_GPS_1123_"
PathRecord = f
PathRecordPath = "./Log/Path/KATECH/KATECH_Path_1123"
PedRecord = f
PedDataPath = "./Log/Ped/KATECH/KATECH_Ped_1123"
IbeoRecord = f
IbeoDataPath = "./Log/Ibeo/KATECH/KATECH_Ibeo_1123"
RadarRecord = f
RadarDataPath = "./Log/Radar/KATECH/KATECH_Radar_1123"

# Path Operation: Save Path -> f, Realtime Path(K-city) -> t
ReceivePathFlag = f
ViewerFlag = t

ReferenceFile = "./Log/GPS/KATECH/KATECH_GPS_1123_23.10.22-11:44:26.txt"
#ReferenceFile = "/home/root/sykim/PathSaveModule/GPS/KATECH/KATECH_0914.txt"
#ReferenceFile = "./Log/GPS/KATECH/KATECH_0914.txt"
#ReferenceFile = "./reference/inclinePath1.txt"

