#[Filter<unique number>]              # filter configration name
#LogAppName=<APID>                    # Name of application to store logs from. Multiple applications can be separated by "," and ".*" denotes all applications
#ContextName=<CTID>                   # Name or names of contexts to store logs from. Multiple contexts can be separated by "," and ".*" denotes all contexts of the application
#LogLevel=<Log level>                 # Define log level, e.g. DLT_LOG_INFO or DLT_LOG_FATAL
#File=<file name>                     # Base name of the created files that containing the logs, e.g. "example". For further file naming scheme configurations see man dlt.conf
#FileSize=<file size in bytes>        # Maximum file size in bytes
#NOFiles=<number of files>            # Number of created files before oldest is deleted and a new one is created
#SyncBehavior=<strategy>              # Specify sync strategy. Default: Sync'ed after every message. See Logstorage Rinbuffer Implementation below.
#EcuID=<ECUid>                        # Specify ECU identifier
#SpecificSize=<spec size in bytes>    # Store logs in storage devices after specific size is reached.

# The Parameter "SyncBehavior","EcuID" and "SpecificSize" are optional - all others are mandatory.
# If both of the parameter "LogAppName" and "ContextName" are set to wildcard or not present in the configuration file, "EcuID" must be specified.

[FILTER1]
LogAppName=.*
ContextName=.*
LogLevel=DLT_LOG_DEBUG
EcuID=Rada
File=RadarFusion
FileSize=16777216
NOFiles=100
SpecificSize=4096
SyncBehavior=ON_DEMAND,ON_DAEMON_EXIT,ON_SPECIFIC_SIZE
