# ---------------------------------------------------------- ###
### ---------------- ControlModule Parameter --------------- ###
# ---------------------------------------------------------- ###
# Control
TargetSpeed = 10 # [kph]

# RECORD
GPSRecord = t# bool
GPSRecordPath = "./data/GPS/"
PathRecord = t
PathRecordPath = "./data/Path/"
VehicleRecord = t
VehicleRecordPath = "./data/Vehicle/"
ControlRecord = f
ControlRecordPath = "./data/Control/"

# Path Operation 
ReceivePathFlag = t # bool
ReferenceFile = "./Reference/230717_PG2.txt"
ExternalIp = "192.168.100.99"
ForwardPort = 1785
BackPort = 3862

# Thread
ViewerFlag = f # bool

# Cycle [ms]
MainCycle = 50

# Communicate
S32GIp = "192.168.100.99"
BroadCastIp = "192.168.100.255"
GPSPort = 3004 # MCU
MCUIp = "192.168.100.88"
MCUPort = 4912
ViewerIp = "192.168.100.35"
ViewerPort = 2817